services:  
  easyproxy:
    image: ghcr.io/realbestia1/easyproxy:full
    container_name: easyproxy
    restart: unless-stopped
    shm_size: "2gb"
    ports:
      - '${PORT:-7860}:${PORT:-7860}' #modifica la variabile "PORT" per cambiare la porta
    environment:
      - API_PASSWORD=ep      #qui inserisci la tua password personalizzata
      - PORT=7860
      - FLARESOLVERR_TIMEOUT=30